--------------------------------------------------------
-- Archivo creado  - domingo-noviembre-19-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CATEGORIAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."CATEGORIAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMPRAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."COMPRAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CONTACTOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."CONTACTOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DETALLESC_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."DETALLESC_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DETALLES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."DETALLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FACTURAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."FACTURAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LOGIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."LOGIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MARCAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."MARCAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUCTOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."PRODUCTOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROLES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."ROLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."USUARIOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CATEGORIAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."CATEGORIAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMPRAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."COMPRAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CONTACTOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."CONTACTOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DETALLESC_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."DETALLESC_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DETALLES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."DETALLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FACTURAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."FACTURAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LOGIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."LOGIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MARCAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."MARCAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUCTOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."PRODUCTOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROLES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."ROLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USUARIOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USR_FERRETERIA"."USUARIOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CATEGORIAS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."CATEGORIAS" 
   (	"ID_CATEGORIA" NUMBER, 
	"NOMBRE_CATEGORIA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPRAS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."COMPRAS" 
   (	"NO_COMPRA" NUMBER, 
	"FECHA_PEDIDO" VARCHAR2(12 BYTE), 
	"PROVEEDOR" VARCHAR2(200 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"COMPRADOR" VARCHAR2(200 BYTE), 
	"TOTAL" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTACTOS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."CONTACTOS" 
   (	"ID_CONTACTO" NUMBER, 
	"NOMBRE_CONTACTO" VARCHAR2(200 BYTE), 
	"CORREO_CONTACTO" VARCHAR2(200 BYTE), 
	"DIRECCION_CONTACTO" VARCHAR2(200 BYTE), 
	"TELEFONO_CONTACTO" NUMBER, 
	"NIT_CONTACTO" VARCHAR2(13 BYTE), 
	"ID_ROL" NUMBER, 
	"IMAGEN_CONTACTO" VARCHAR2(200 BYTE) DEFAULT 'imgbd/no contacto.jpg'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLES_COMPRA
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."DETALLES_COMPRA" 
   (	"ID_DETALLEC" NUMBER, 
	"NO_COMPRA" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"CANTIDAD" NUMBER, 
	"PRECIO" FLOAT(126), 
	"SUBTOTAL" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLES_FACTURA
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."DETALLES_FACTURA" 
   (	"ID_DETALLE" NUMBER, 
	"NO_FACTURA" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"CANTIDAD" NUMBER, 
	"PRECIO" FLOAT(126), 
	"SUBTOTAL" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACTURAS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."FACTURAS" 
   (	"NO_FACTURA" NUMBER, 
	"FECHA_EMISION" VARCHAR2(12 BYTE), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"NIT" NUMBER(*,0), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"VENDEDOR" VARCHAR2(200 BYTE), 
	"TOTAL" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."LOGIN" 
   (	"ID_LOGIN" NUMBER, 
	"CORREO" VARCHAR2(200 BYTE), 
	"CONTRASENA" VARCHAR2(200 BYTE), 
	"ID_ROL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MARCAS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."MARCAS" 
   (	"ID_MARCA" NUMBER, 
	"NOMBRE_MARCA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDENES
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."ORDENES" 
   (	"ORDEN_COMPRA" VARCHAR2(200 BYTE), 
	"PROVEEDOR" VARCHAR2(200 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"FECHA" VARCHAR2(200 BYTE), 
	"PRODUCTO" VARCHAR2(200 BYTE), 
	"CANTIDAD" VARCHAR2(200 BYTE), 
	"PRECIO" VARCHAR2(200 BYTE), 
	"SUBTOTAL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."PRODUCTOS" 
   (	"ID_PRODUCTO" NUMBER, 
	"NOMBRE_PRODUCTO" VARCHAR2(200 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"ID_CATEGORIA" NUMBER(*,0), 
	"ID_MARCA" NUMBER(*,0), 
	"PRECIO" FLOAT(126), 
	"EXISTENCIA" NUMBER(*,0), 
	"IMAGEN" VARCHAR2(200 BYTE) DEFAULT 'imgbd/no producto.jpg', 
	"COSTE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."ROLES" 
   (	"ID_ROL" NUMBER, 
	"NOMBRE_ROL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."USUARIOS" 
   (	"ID_USUARIO" NUMBER, 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"CORREO" VARCHAR2(200 BYTE), 
	"CONTRASENA" VARCHAR2(50 BYTE), 
	"ID_ROL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENTAS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."VENTAS" 
   (	"NO_VENTA" VARCHAR2(200 BYTE), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"NIT" VARCHAR2(200 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"FECHA" VARCHAR2(200 BYTE), 
	"PRODUCTO" VARCHAR2(200 BYTE), 
	"CANTIDAD" VARCHAR2(200 BYTE), 
	"PRECIO" VARCHAR2(200 BYTE), 
	"SUBTOTAL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACTURAS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."FACTURAS" 
   (	"NO_FACTURA" NUMBER, 
	"FECHA_EMISION" VARCHAR2(12 BYTE), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"NIT" NUMBER(*,0), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"VENDEDOR" VARCHAR2(200 BYTE), 
	"TOTAL" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."ROLES" 
   (	"ID_ROL" NUMBER, 
	"NOMBRE_ROL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIAS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."CATEGORIAS" 
   (	"ID_CATEGORIA" NUMBER, 
	"NOMBRE_CATEGORIA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MARCAS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."MARCAS" 
   (	"ID_MARCA" NUMBER, 
	"NOMBRE_MARCA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTACTOS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."CONTACTOS" 
   (	"ID_CONTACTO" NUMBER, 
	"NOMBRE_CONTACTO" VARCHAR2(200 BYTE), 
	"CORREO_CONTACTO" VARCHAR2(200 BYTE), 
	"DIRECCION_CONTACTO" VARCHAR2(200 BYTE), 
	"TELEFONO_CONTACTO" NUMBER, 
	"NIT_CONTACTO" VARCHAR2(13 BYTE), 
	"ID_ROL" NUMBER, 
	"IMAGEN_CONTACTO" VARCHAR2(200 BYTE) DEFAULT 'imgbd/no contacto.jpg'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLES_FACTURA
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."DETALLES_FACTURA" 
   (	"ID_DETALLE" NUMBER, 
	"NO_FACTURA" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"CANTIDAD" NUMBER, 
	"PRECIO" FLOAT(126), 
	"SUBTOTAL" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."LOGIN" 
   (	"ID_LOGIN" NUMBER, 
	"CORREO" VARCHAR2(200 BYTE), 
	"CONTRASENA" VARCHAR2(200 BYTE), 
	"ID_ROL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."PRODUCTOS" 
   (	"ID_PRODUCTO" NUMBER, 
	"NOMBRE_PRODUCTO" VARCHAR2(200 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"ID_CATEGORIA" NUMBER(*,0), 
	"ID_MARCA" NUMBER(*,0), 
	"PRECIO" FLOAT(126), 
	"EXISTENCIA" NUMBER(*,0), 
	"IMAGEN" VARCHAR2(200 BYTE) DEFAULT 'imgbd/no producto.jpg', 
	"COSTE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."USUARIOS" 
   (	"ID_USUARIO" NUMBER, 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"CORREO" VARCHAR2(200 BYTE), 
	"CONTRASENA" VARCHAR2(50 BYTE), 
	"ID_ROL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPRAS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."COMPRAS" 
   (	"NO_COMPRA" NUMBER, 
	"FECHA_PEDIDO" VARCHAR2(12 BYTE), 
	"PROVEEDOR" VARCHAR2(200 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"COMPRADOR" VARCHAR2(200 BYTE), 
	"TOTAL" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLES_COMPRA
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."DETALLES_COMPRA" 
   (	"ID_DETALLEC" NUMBER, 
	"NO_COMPRA" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"CANTIDAD" NUMBER, 
	"PRECIO" FLOAT(126), 
	"SUBTOTAL" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDENES
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."ORDENES" 
   (	"ORDEN_COMPRA" VARCHAR2(200 BYTE), 
	"PROVEEDOR" VARCHAR2(200 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"FECHA" VARCHAR2(200 BYTE), 
	"PRODUCTO" VARCHAR2(200 BYTE), 
	"CANTIDAD" VARCHAR2(200 BYTE), 
	"PRECIO" VARCHAR2(200 BYTE), 
	"SUBTOTAL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENTAS
--------------------------------------------------------

  CREATE TABLE "USR_FERRETERIA"."VENTAS" 
   (	"NO_VENTA" VARCHAR2(200 BYTE), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"NIT" VARCHAR2(200 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"FECHA" VARCHAR2(200 BYTE), 
	"PRODUCTO" VARCHAR2(200 BYTE), 
	"CANTIDAD" VARCHAR2(200 BYTE), 
	"PRECIO" VARCHAR2(200 BYTE), 
	"SUBTOTAL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USR_FERRETERIA.CATEGORIAS
SET DEFINE OFF;
Insert into USR_FERRETERIA.CATEGORIAS (ID_CATEGORIA,NOMBRE_CATEGORIA) values (1,'Herramientas');
Insert into USR_FERRETERIA.CATEGORIAS (ID_CATEGORIA,NOMBRE_CATEGORIA) values (2,'Electricos');
Insert into USR_FERRETERIA.CATEGORIAS (ID_CATEGORIA,NOMBRE_CATEGORIA) values (3,'Jardinería');
Insert into USR_FERRETERIA.CATEGORIAS (ID_CATEGORIA,NOMBRE_CATEGORIA) values (4,'Construcción');
Insert into USR_FERRETERIA.CATEGORIAS (ID_CATEGORIA,NOMBRE_CATEGORIA) values (5,'Plomería');
REM INSERTING into USR_FERRETERIA.COMPRAS
SET DEFINE OFF;
REM INSERTING into USR_FERRETERIA.CONTACTOS
SET DEFINE OFF;
REM INSERTING into USR_FERRETERIA.DETALLES_COMPRA
SET DEFINE OFF;
REM INSERTING into USR_FERRETERIA.DETALLES_FACTURA
SET DEFINE OFF;
REM INSERTING into USR_FERRETERIA.FACTURAS
SET DEFINE OFF;
REM INSERTING into USR_FERRETERIA.LOGIN
SET DEFINE OFF;
REM INSERTING into USR_FERRETERIA.MARCAS
SET DEFINE OFF;
Insert into USR_FERRETERIA.MARCAS (ID_MARCA,NOMBRE_MARCA) values (1,'Total');
Insert into USR_FERRETERIA.MARCAS (ID_MARCA,NOMBRE_MARCA) values (2,'Truper');
Insert into USR_FERRETERIA.MARCAS (ID_MARCA,NOMBRE_MARCA) values (3,'Bosch');
Insert into USR_FERRETERIA.MARCAS (ID_MARCA,NOMBRE_MARCA) values (4,'Luxlite');
Insert into USR_FERRETERIA.MARCAS (ID_MARCA,NOMBRE_MARCA) values (5,'DeWalt');
REM INSERTING into USR_FERRETERIA.ORDENES
SET DEFINE OFF;
REM INSERTING into USR_FERRETERIA.PRODUCTOS
SET DEFINE OFF;
REM INSERTING into USR_FERRETERIA.ROLES
SET DEFINE OFF;
Insert into USR_FERRETERIA.ROLES (ID_ROL,NOMBRE_ROL) values (1,'Cliente');
Insert into USR_FERRETERIA.ROLES (ID_ROL,NOMBRE_ROL) values (2,'Proveedor');
REM INSERTING into USR_FERRETERIA.USUARIOS
SET DEFINE OFF;
Insert into USR_FERRETERIA.USUARIOS (ID_USUARIO,NOMBRE,CORREO,CONTRASENA,ID_ROL) values (1,'Jarod Mejía','admin@ferreteria.com','123',1);
REM INSERTING into USR_FERRETERIA.VENTAS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_CATEGORIAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_CATEGORIAS" ON "USR_FERRETERIA"."CATEGORIAS" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CLIENTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_CLIENTES" ON "USR_FERRETERIA"."CONTACTOS" ("ID_CONTACTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DETALLES
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_DETALLES" ON "USR_FERRETERIA"."DETALLES_FACTURA" ("ID_DETALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FACTURAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_FACTURAS" ON "USR_FERRETERIA"."FACTURAS" ("NO_FACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LOGIN
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_LOGIN" ON "USR_FERRETERIA"."LOGIN" ("ID_LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MARCAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_MARCAS" ON "USR_FERRETERIA"."MARCAS" ("ID_MARCA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCTOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_PRODUCTOS" ON "USR_FERRETERIA"."PRODUCTOS" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ROLES
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_ROLES" ON "USR_FERRETERIA"."ROLES" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_USUARIOS" ON "USR_FERRETERIA"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CATEGORIAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_CATEGORIAS" ON "USR_FERRETERIA"."CATEGORIAS" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CLIENTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_CLIENTES" ON "USR_FERRETERIA"."CONTACTOS" ("ID_CONTACTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DETALLES
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_DETALLES" ON "USR_FERRETERIA"."DETALLES_FACTURA" ("ID_DETALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FACTURAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_FACTURAS" ON "USR_FERRETERIA"."FACTURAS" ("NO_FACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LOGIN
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_LOGIN" ON "USR_FERRETERIA"."LOGIN" ("ID_LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MARCAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_MARCAS" ON "USR_FERRETERIA"."MARCAS" ("ID_MARCA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCTOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_PRODUCTOS" ON "USR_FERRETERIA"."PRODUCTOS" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ROLES
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_ROLES" ON "USR_FERRETERIA"."ROLES" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "USR_FERRETERIA"."PK_USUARIOS" ON "USR_FERRETERIA"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CATEGORIAS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."CATEGORIAS_TRG" 
BEFORE INSERT ON CATEGORIAS
FOR EACH ROW
BEGIN
    SELECT CATEGORIAS_SEQ.NEXTVAL INTO :NEW.ID_CATEGORIA FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."CATEGORIAS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMPRAS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."COMPRAS_TRG" 
BEFORE INSERT ON COMPRAS
FOR EACH ROW
BEGIN
    SELECT COMPRAS_SEQ.NEXTVAL INTO :NEW.NO_COMPRA FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."COMPRAS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTACTOS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."CONTACTOS_TRG" 
BEFORE INSERT ON CONTACTOS
FOR EACH ROW
BEGIN
    SELECT CONTACTOS_SEQ.NEXTVAL INTO :NEW.ID_CONTACTO FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."CONTACTOS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DETALLESC_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."DETALLESC_TRG" 
BEFORE INSERT ON DETALLES_COMPRA
FOR EACH ROW
BEGIN
    SELECT DETALLESC_SEQ.NEXTVAL INTO :NEW.ID_DETALLEC FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."DETALLESC_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DETALLES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."DETALLES_TRG" 
BEFORE INSERT ON DETALLES_FACTURA
FOR EACH ROW
BEGIN
    SELECT DETALLES_SEQ.NEXTVAL INTO :NEW.ID_DETALLE FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."DETALLES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FACTURAS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."FACTURAS_TRG" 
BEFORE INSERT ON FACTURAS
FOR EACH ROW
BEGIN
    SELECT FACTURAS_SEQ.NEXTVAL INTO :NEW.NO_FACTURA FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."FACTURAS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOGIN_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."LOGIN_TRG" 
BEFORE INSERT ON LOGIN
FOR EACH ROW
BEGIN
    SELECT LOGIN_SEQ.NEXTVAL INTO :NEW.ID_LOGIN FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."LOGIN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MARCAS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."MARCAS_TRG" 
BEFORE INSERT ON MARCAS
FOR EACH ROW
BEGIN
    SELECT MARCAS_SEQ.NEXTVAL INTO :NEW.ID_MARCA FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."MARCAS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDENES
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."ORDENES" 
BEFORE INSERT ON ORDENES
FOR EACH ROW
BEGIN
  UPDATE PRODUCTOS SET EXISTENCIA = EXISTENCIA + :NEW.CANTIDAD WHERE NOMBRE_PRODUCTO = :NEW.PRODUCTO;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."ORDENES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCTOS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."PRODUCTOS_TRG" 
BEFORE INSERT ON PRODUCTOS
FOR EACH ROW
BEGIN
    SELECT PRODUCTOS_SEQ.NEXTVAL INTO :NEW.ID_PRODUCTO FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."PRODUCTOS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROLES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."ROLES_TRG" 
BEFORE INSERT ON ROLES
FOR EACH ROW
BEGIN
    SELECT ROLES_SEQ.NEXTVAL INTO :NEW.ID_ROL FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."ROLES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USUARIOS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."USUARIOS_TRG" 
BEFORE INSERT ON USUARIOS
FOR EACH ROW
BEGIN
    SELECT USUARIOS_SEQ.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."USUARIOS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VENTA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."VENTA" 
BEFORE INSERT ON VENTAS
FOR EACH ROW
BEGIN
  UPDATE PRODUCTOS SET EXISTENCIA = EXISTENCIA - :NEW.CANTIDAD WHERE NOMBRE_PRODUCTO = :NEW.PRODUCTO;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."VENTA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATEGORIAS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."CATEGORIAS_TRG" 
BEFORE INSERT ON CATEGORIAS
FOR EACH ROW
BEGIN
    SELECT CATEGORIAS_SEQ.NEXTVAL INTO :NEW.ID_CATEGORIA FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."CATEGORIAS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMPRAS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."COMPRAS_TRG" 
BEFORE INSERT ON COMPRAS
FOR EACH ROW
BEGIN
    SELECT COMPRAS_SEQ.NEXTVAL INTO :NEW.NO_COMPRA FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."COMPRAS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTACTOS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."CONTACTOS_TRG" 
BEFORE INSERT ON CONTACTOS
FOR EACH ROW
BEGIN
    SELECT CONTACTOS_SEQ.NEXTVAL INTO :NEW.ID_CONTACTO FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."CONTACTOS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DETALLESC_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."DETALLESC_TRG" 
BEFORE INSERT ON DETALLES_COMPRA
FOR EACH ROW
BEGIN
    SELECT DETALLESC_SEQ.NEXTVAL INTO :NEW.ID_DETALLEC FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."DETALLESC_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DETALLES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."DETALLES_TRG" 
BEFORE INSERT ON DETALLES_FACTURA
FOR EACH ROW
BEGIN
    SELECT DETALLES_SEQ.NEXTVAL INTO :NEW.ID_DETALLE FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."DETALLES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FACTURAS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."FACTURAS_TRG" 
BEFORE INSERT ON FACTURAS
FOR EACH ROW
BEGIN
    SELECT FACTURAS_SEQ.NEXTVAL INTO :NEW.NO_FACTURA FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."FACTURAS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOGIN_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."LOGIN_TRG" 
BEFORE INSERT ON LOGIN
FOR EACH ROW
BEGIN
    SELECT LOGIN_SEQ.NEXTVAL INTO :NEW.ID_LOGIN FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."LOGIN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MARCAS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."MARCAS_TRG" 
BEFORE INSERT ON MARCAS
FOR EACH ROW
BEGIN
    SELECT MARCAS_SEQ.NEXTVAL INTO :NEW.ID_MARCA FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."MARCAS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDENES
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."ORDENES" 
BEFORE INSERT ON ORDENES
FOR EACH ROW
BEGIN
  UPDATE PRODUCTOS SET EXISTENCIA = EXISTENCIA + :NEW.CANTIDAD WHERE NOMBRE_PRODUCTO = :NEW.PRODUCTO;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."ORDENES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCTOS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."PRODUCTOS_TRG" 
BEFORE INSERT ON PRODUCTOS
FOR EACH ROW
BEGIN
    SELECT PRODUCTOS_SEQ.NEXTVAL INTO :NEW.ID_PRODUCTO FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."PRODUCTOS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROLES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."ROLES_TRG" 
BEFORE INSERT ON ROLES
FOR EACH ROW
BEGIN
    SELECT ROLES_SEQ.NEXTVAL INTO :NEW.ID_ROL FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."ROLES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USUARIOS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."USUARIOS_TRG" 
BEFORE INSERT ON USUARIOS
FOR EACH ROW
BEGIN
    SELECT USUARIOS_SEQ.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."USUARIOS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VENTA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USR_FERRETERIA"."VENTA" 
BEFORE INSERT ON VENTAS
FOR EACH ROW
BEGIN
  UPDATE PRODUCTOS SET EXISTENCIA = EXISTENCIA - :NEW.CANTIDAD WHERE NOMBRE_PRODUCTO = :NEW.PRODUCTO;
END;
/
ALTER TRIGGER "USR_FERRETERIA"."VENTA" ENABLE;
--------------------------------------------------------
--  DDL for Synonymn DUAL
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DUAL" FOR "SYS"."DUAL";
--------------------------------------------------------
--  Constraints for Table CATEGORIAS
--------------------------------------------------------

  ALTER TABLE "USR_FERRETERIA"."CATEGORIAS" ADD CONSTRAINT "PK_CATEGORIAS" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTACTOS
--------------------------------------------------------

  ALTER TABLE "USR_FERRETERIA"."CONTACTOS" ADD CONSTRAINT "PK_CLIENTES" PRIMARY KEY ("ID_CONTACTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLES_FACTURA
--------------------------------------------------------

  ALTER TABLE "USR_FERRETERIA"."DETALLES_FACTURA" ADD CONSTRAINT "PK_DETALLES" PRIMARY KEY ("ID_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURAS
--------------------------------------------------------

  ALTER TABLE "USR_FERRETERIA"."FACTURAS" ADD CONSTRAINT "PK_FACTURAS" PRIMARY KEY ("NO_FACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "USR_FERRETERIA"."LOGIN" ADD CONSTRAINT "PK_LOGIN" PRIMARY KEY ("ID_LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MARCAS
--------------------------------------------------------

  ALTER TABLE "USR_FERRETERIA"."MARCAS" ADD CONSTRAINT "PK_MARCAS" PRIMARY KEY ("ID_MARCA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "USR_FERRETERIA"."PRODUCTOS" ADD CONSTRAINT "PK_PRODUCTOS" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "USR_FERRETERIA"."ROLES" ADD CONSTRAINT "PK_ROLES" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "USR_FERRETERIA"."USUARIOS" ADD CONSTRAINT "PK_USUARIOS" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLES_FACTURA
--------------------------------------------------------

  ALTER TABLE "USR_FERRETERIA"."DETALLES_FACTURA" ADD CONSTRAINT "FK_DETALLES_FACTURAS" FOREIGN KEY ("NO_FACTURA")
	  REFERENCES "USR_FERRETERIA"."FACTURAS" ("NO_FACTURA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "USR_FERRETERIA"."LOGIN" ADD CONSTRAINT "FK_LOGIN_ROLES" FOREIGN KEY ("ID_ROL")
	  REFERENCES "USR_FERRETERIA"."ROLES" ("ID_ROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "USR_FERRETERIA"."PRODUCTOS" ADD CONSTRAINT "FK_PRODUCTOS_CATEGORIAS" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "USR_FERRETERIA"."CATEGORIAS" ("ID_CATEGORIA") ENABLE;
  ALTER TABLE "USR_FERRETERIA"."PRODUCTOS" ADD CONSTRAINT "FK_PRODUCTOS_MARCAS" FOREIGN KEY ("ID_MARCA")
	  REFERENCES "USR_FERRETERIA"."MARCAS" ("ID_MARCA") ENABLE;
